### ISSUE TITLE
add stations and popup

### ISSUE THREAD

**Issue by simgislab** [nextgis/metrocell#3]
popup should show station name and id

**Comment by simgislab** [comment]
Where station points are from? Seem to be different from the ones from here: http://metro4all.org/ru/msk

**Comment by KolesovDmitry** [comment]
Commit https://github.com/nextgis/metrocell/commit/a61deba62b6f807cd5d254d64717dd68060c08ba fixes the issue. We use http://metro4all.org/ru/msk data now.

**Comment by simgislab** [comment]
good enough
